spring:
  jwt:
    secret: dydghksdydghksdydghksdydghksaaaaaaaaaaaaaaaaa
    header: Authorization
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6
#Email 인증
mail:
  host: smtp.gmail.com
  port: 587
  username: ghks4421@gmail.com
  password: darh wvwh bzse wicf
  supplier: gmail
  from-mail: ghks4421@gmail.com
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
  auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30?